python unihsi/run.py \
    --task UniHSI_PartNet_Test\
    --test \
    --num_envs 256 \
    --cfg_env unihsi/data/cfg/humanoid_unified_interaction_scene_16_simple.yaml \
    --cfg_train unihsi/data/cfg/train/rlg/amp_humanoid_task_deep_layer_test.yaml \
    --motion_file motion_clips/armchair.npy \
    --output_path output/ \
    --headless \
    --checkpoint checkpoints/Humanoid.pth \
    --obj_file sceneplan/partnet_test_simple_partnet.json